<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1" ProductVersion="3.1.4024.12">
  <POU Name="RET_COMMON" Id="{371f0054-3649-4ee2-83d9-b6a67901040c}" SpecialFunc="None">
    <Declaration><![CDATA[{attribute 'hide_all_locals' := ''}
PROGRAM RET_COMMON
VAR_INPUT
	/// Zykluszeit Main-Task
	fDt: REAL := 0.002;
END_VAR
]]></Declaration>
    <Implementation>
      <ST><![CDATA[]]></ST>
    </Implementation>
    <LineIds Name="RET_COMMON">
      <LineId Id="2" Count="0" />
    </LineIds>
  </POU>
</TcPlcObject>