<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1" ProductVersion="3.1.4024.12">
  <POU Name="TOUCH_SCALE" Id="{71c40a65-c64c-4ba4-8987-c19dffd73ba3}" SpecialFunc="None">
    <Declaration><![CDATA[FUNCTION_BLOCK TOUCH_SCALE
VAR_INPUT
	rX: REAL;  // ADC-Wert
	rDistance: REAL;  // physikalisch, gültige Länge [mm]
	rMinAdc: REAL;  // kleinster, gültiger ADC-Wert
	rMaxAdc: REAL;  // grösster, gültiger ADC-Wert
	rOffset : REAL;
END_VAR
VAR_OUTPUT
	rX_mm: REAL;  // Skalierung in mm
END_VAR

]]></Declaration>
    <Implementation>
      <ST><![CDATA[rX_mm := (rX - rMinAdc) * rDistance/(rMaxAdc - rMinAdc) - rOffset;]]></ST>
    </Implementation>
    <LineIds Name="TOUCH_SCALE">
      <LineId Id="751" Count="0" />
    </LineIds>
  </POU>
</TcPlcObject>